project/about/urls.py
from django.urls import path

from .views import AboutView


urlpatterns = [
    path('', AboutView.as_view(), name='about'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import RedirectView
from django.utils.translation import ugettext_lazy as _


urlpatterns = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('project.home.urls')),
    path('', include('django.conf.urls.i18n')),
    path('', include('project.program.urls')),
    path('partners/', include('project.partners.urls')),
    path('about/', include('project.about.urls')),
)

admin.site.site_header = _('TEDxNTUA 2020 administration')
admin.site.site_title = _('TEDxNTUA 2020 admin')

project/team/models.py
from django.db import models
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _

from parler.models import TranslatableModel, TranslatedFields
from parler.managers import TranslatableManager
from versatileimagefield.fields import VersatileImageField
from versatileimagefield.image_warmer import VersatileImageFieldWarmer


class TeamMemberManager(TranslatableManager):
    def get_teams(self, unpublished=False):
        '''
        Table-level method to get all team members grouped by team.

        Parameters
        ----------
        unpublished : bool (default False)
            Controls if unpublished team members are included.

        Returns
        -------
        directory : dict
            A dictionary where team IDs from TeamMember.TEAM_CHOICES
            are the keys and the value is a dictionary with the `title` of
            the team and a `members` array.

            The order of teams is the same as in TEAM_CHOICES.
        '''
        teams = {}
        for team_id, title in TeamMember.TEAM_CHOICES:
            teams[team_id] = {
                'title': title,
                'members': [],
            }

        qs = self.get_queryset()
        if not unpublished:
            qs = qs.filter(is_published=True)

        for member in qs:
            teams[member.team]['members'].append(member)
        return teams

    def published(self):
        return self.get_queryset().filter(is_published=True)


class TeamMember(TranslatableModel):
    '''
    Model for members of the TEDxNTUA organizing team.

    The `team` attribute is represented as a CharField with limited possible
    values. The definition follows the official documentation example:
    https://docs.djangoproject.com/en/2.2/ref/models/fields/#choices
    '''
    EXPERIENCE = 'experience'
    IT = 'it'
    FUNDRAISING = 'fundraising'
    GRAPHICS = 'graphics'
    MEDIA = 'media'
    SPEAKERS = 'speakers'
    VENUE_PRODUCTION = 'venue-production'
    TEAM_CHOICES = (
        (EXPERIENCE, 'Experience'),
        (IT, 'IT'),
        (FUNDRAISING, 'Fundraising'),
        (GRAPHICS, 'Graphics'),
        (MEDIA, 'Media'),
        (SPEAKERS, 'Speakers'),
        (VENUE_PRODUCTION, 'Venue & Production'),
    )
    translations = TranslatedFields(
        name=models.CharField(max_length=255, default='')
    )
    email = models.EmailField()
    team = models.CharField(max_length=16, choices=TEAM_CHOICES)

    image = VersatileImageField(
        'Image 1',
        upload_to='team/',
        width_field='image_width',
        height_field='image_height',
        null=True,
        blank=True,
    )
    image_height = models.PositiveIntegerField(editable=False, null=True)
    image_width = models.PositiveIntegerField(editable=False, null=True)

    image_alt = VersatileImageField(
        'Image 2',
        upload_to='team/',
        width_field='image_alt_width',
        height_field='image_alt_height',
        null=True,
        blank=True,
    )
    image_alt_height = models.PositiveIntegerField(editable=False, null=True)
    image_alt_width = models.PositiveIntegerField(editable=False, null=True)

    is_published = models.BooleanField(_('Published'), default=True)

    objects = TeamMemberManager()

    def __str__(self):
        '''
        Objects of the TeamMember class are represented as strings by
        their fullname property
        '''
        return self.name


@receiver(models.signals.post_save, sender=TeamMember)
def warm_team_member_images(sender, instance, **kwargs):
    '''
    Ensures images are created post-save.
    Image sizes are stored in base.VERSATILEIMAGEFIELD_RENDITION_KEY_SETS.
    Using a thumbnail__AxA rendition key, the image fits in a AxA rectangle by
    maintaining the aspect ratio.

    Documentation link:
    https://django-versatileimagefield.readthedocs.io/en/latest/overview.html#create-images-wherever-you-need-them
    '''

    for field in ['image', 'image_alt']:
        img_warmer = VersatileImageFieldWarmer(
            instance_or_queryset=instance,
            rendition_key_set='Sizes',
            image_attr=field,
            verbose=True
        )
        img_warmer.warm()

project/about/views.py
from django.conf import settings
from django.shortcuts import render
from django.views import View

from project.team.models import TeamMember


class AboutView(View):
    template_name = 'about/index.html'

    def get(self, request):
        if settings.TEDXNTUA_SHOW_UNPUBLISHED:
            members = TeamMember.objects.all()
        else:
            members = TeamMember.objects.published()

        return render(request, self.template_name, {
            'members': members,
        })

project/about/templates/about/index.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load render_bundle from webpack_loader %}
{% block title %}{% trans 'about.title' %}{% endblock %}
{% block description %}{% trans 'about.description' %}{% endblock %}
{% block image %}{% static "images/tedxntua_photo_1200.jpg" %}{% endblock %}
{% block content %}
<article class="about-page">
    <section id="team">
        <div id="simple-view">
            <header>
                <h2>{% trans 'about.meet_the_team' %}</h2>
            </header>
            {% for member in members %}
            <div class="member">
                <div class="slider-image normal">
                    {% if member.image %}
                    <img class="lazy lazy-on-hover" data-loaded="false"
                        src="{{ member.image.thumbnail.320x320.url }}"
                        data-srcset="{{ member.image.thumbnail.320x320.url }} 320w,
                            {{ member.image.thumbnail.720x720.url }} 720w,
                            {{ member.image.thumbnail.1024x1024.url }} 1024w"
                        sizes="(max-width: 576px) 320px,
                            (max-width: 992px) 720px,
                            1024px"
                        alt="" />
                    {% endif %}
                    <p>{{ member.name }}</p>
                </div>
                <div class="slider-image on-hover">
                    {% if member.image_alt %}
                    <img class="lazy lazy-on-hover" data-loaded="false"
                        src="{{ member.image_alt.thumbnail.320x320.url }}"
                        data-srcset="{{ member.image_alt.thumbnail.320x320.url }} 320w,
                            {{ member.image_alt.thumbnail.720x720.url }} 720w,
                            {{ member.image_alt.thumbnail.1024x1024.url }} 1024w"
                        sizes="(max-width: 576px) 320px,
                            (max-width: 992px) 720px,
                            1024px"
                        alt="" />
                    {% endif %}
                    <p>
                        {% blocktrans trimmed with team_name=member.get_team_display|upper %}
                            {{ team_name }} TEAM
                        {% endblocktrans %}
                    </p>
                </div>
            </div>
            {% endfor %}
        </div>
        <div id="cube-view"></div>
    </section>
    <section id="about">
        <img class="lazy lazy-on-view"
            src="{% static "images/tedxntua_photo_540.jpg" %}"
            data-srcset="{% static "images/tedxntua_photo_540.jpg" %} 540w,
                     {% static "images/tedxntua_photo_1200.jpg" %} 1200w,
                     {% static "images/tedxntua_photo_2400.jpg" %} 2400w"
            sizes="(max-width: 768px) 540px,
                    (max-width: 1440px) 1200px,
                    2400px"
            alt="TEDxNTUA organizing team and volunteers celebrating the conclusion of the 2019 event" />
        <div class="about-section" id="about-tedxntua">
            {% trans 'about.tedxntua' %}
            {% trans 'about.join' %}
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 col-md-6 about-section" id="about-ted">
                    {% trans 'about.ted' %}
                </div>
                <div class="col-12 col-md-6 about-section" id="about-tedx">
                    {% trans 'about.tedx' %}
                </div>
            </div>
        </div>
    </section>
</article>
{% endblock %}
{% block scripts %}
    {% render_bundle 'about' 'js' %}
{% endblock %}